spring.application.name=Employee
# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=9999
#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Server
server.port=8080

#Logging
logging.level.root=INFO
logging.level.com.employee=DEBUG



